### ISSUE TITLE
CPU-GPU scheme

### ISSUE THREAD

**Issue by JonathanLehner** [diditforlulz273/PokerRL-Omaha#5]
Where is the code for the CPU:-GPU training scheme? for me it is not using the GPU

**Comment by diditforlulz273** [comment]
Hi Jonathan!
You can try running the code in a CPU mode by setting PyTorch's param device to 'cpu' rather than 'cuda:0' everywhere in the code.
There is no specific switch for it as training in a CPU-only mode would take ages :)
