### ISSUE TITLE
Memory usage grows rapidly in SD-CFR 

### ISSUE THREAD

**Issue by Bender1019** [diditforlulz273/PokerRL-Omaha#8]
As strategies buffer grows, memory usage grows rapidly, because every strategy copy its own lookup table inside its network. In my situation, memory grows out of memory at iteration 300+... 
Every lookup table in the strategy are transferred into float32 occupying more than 800mb memory which make model training and serving impossible.

**Comment by diditforlulz273** [comment]
I don't remember having issues with RAM overflow, but you might be right.
I am sorry to say, but I can not do anything about this as I have no interest in supporting this code - use it at your own experience.

**Comment by Bender1019** [comment]
Thanks for reply, I would have a try.
